name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update ubuntu
      run: sudo mkdir -p /data/data/com.termux/files/usr
    - name: setup-ubuntu
      run: ./scripts/setup-ubuntu.sh
